plugins {
	id 'me.champeau.jmh' version '0.7.2'
}

def findProjectUtility = project.parent.ext.findProjectByName
def generatorProjectRef = findProjectUtility.call('generator')
tasks.named('processResources') {
    // La tâche 'classes' dépend maintenant de la préparation des ressources générées
    dependsOn(generatorProjectRef.tasks.named('generate'))
}
tasks.named('processTestResources') {
    // La tâche 'classes' dépend maintenant de la préparation des ressources générées
    dependsOn(generatorProjectRef.tasks.named('generate'))
}
tasks.named('clean') {
    dependsOn(generatorProjectRef.tasks.named('cleanGenerate'))
}

sourceSets {
	main {
		resources.srcDirs += 'src/main/generated-resources'
	}
}


testing {
	suites {
		test {
			useJUnitJupiter()
		}
	}
}

jmh {
	includes = ['Evaluator']
	fork = 2
	iterations = 5
	jmhVersion = '1.37'
}