plugins {
    id("com.diffplug.spotless") version "8.1.0"
}

allprojects {
	group = 'io.github.kennethshackleton.skpokereval'
	version = '1.10.0-SNAPSHOT'
	
	repositories {
		mavenCentral()
	}
}

ext.findProjectByName = { String projectName ->
    // Parcourir TOUS les projets de la hiérarchie du build (même les projets inclus)
    // et trouver celui dont le nom simple correspond.
    def foundProject = rootProject.allprojects.find { p ->
        p.name == projectName
    }

    // Retourner la référence du projet ou null
    return foundProject
}

subprojects {
	apply plugin: 'java'
    apply plugin: 'com.diffplug.spotless'

	java {
		sourceCompatibility = '17'
		targetCompatibility = '17'
	}
    spotless {
        java {
            palantirJavaFormat()
        }
    }

    tasks.named('check') {
        dependsOn spotlessCheck
    }
}

